// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCK1M19IEiIl0n0Z5sx3t7H_63LaJTmt4',
    appId: '1:173598418186:web:712965360a4e3c5a3d46f3',
    messagingSenderId: '173598418186',
    projectId: 'my-good-firestoreproject',
    authDomain: 'my-good-firestoreproject.firebaseapp.com',
    storageBucket: 'my-good-firestoreproject.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDoucJGhr5B0QFT-L8x8pc48NfCdyCg7pI',
    appId: '1:173598418186:android:9900219f3e6d8cf43d46f3',
    messagingSenderId: '173598418186',
    projectId: 'my-good-firestoreproject',
    storageBucket: 'my-good-firestoreproject.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSoZQSm_Q3OfcdK4rpuR-yTjN5FKpSTVA',
    appId: '1:173598418186:ios:c2a42844c171a5853d46f3',
    messagingSenderId: '173598418186',
    projectId: 'my-good-firestoreproject',
    storageBucket: 'my-good-firestoreproject.appspot.com',
    iosClientId: '173598418186-05vgtnr8i2m2r6j4van4tba4fmu80vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterclass9th',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSoZQSm_Q3OfcdK4rpuR-yTjN5FKpSTVA',
    appId: '1:173598418186:ios:c2a42844c171a5853d46f3',
    messagingSenderId: '173598418186',
    projectId: 'my-good-firestoreproject',
    storageBucket: 'my-good-firestoreproject.appspot.com',
    iosClientId: '173598418186-05vgtnr8i2m2r6j4van4tba4fmu80vat.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterclass9th',
  );
}
